// <auto-generated />
using System;
using Examen.API.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.API.Data.Migrations
{
    [DbContext(typeof(ExamenContext))]
    [Migration("20250518083729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Examen.API.Data.Models.TblFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<int>("IdPersona")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_persona");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT")
                        .HasColumnName("monto");

                    b.HasKey("Id");

                    b.HasIndex("IdPersona");

                    b.ToTable("tbl_factura", (string)null);
                });

            modelBuilder.Entity("Examen.API.Data.Models.TblPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellidoMaterno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellidoPaterno");

                    b.Property<int>("Identificacion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.ToTable("tbl_persona", (string)null);
                });

            modelBuilder.Entity("Examen.API.Data.Models.TblFactura", b =>
                {
                    b.HasOne("Examen.API.Data.Models.TblPersona", "IdPersonaNavigation")
                        .WithMany("TblFacturas")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK_tbl_factura_tbl_persona");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("Examen.API.Data.Models.TblPersona", b =>
                {
                    b.Navigation("TblFacturas");
                });
#pragma warning restore 612, 618
        }
    }
}
